version: "3.8"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    tty: true 
    environment:
      - POSTGRES_HOST=database
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - database
