name: Integration

on:
  schedule:
  - cron: "0 0 * * *"
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build frontend
      run: |
        cd frontend
        yarn install
        yarn build --silent
    - uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: backend
    - name: Load database from schema
      run: |
        cd backend
        bundle exec bin/rails db:schema:load
    - name: Load fixtures to database
      env:
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails db:fixtures:load
    - name: Run rails backend
      env:
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails s &
    - name: Run e2e tests
      run: |
        cd frontend
        yarn cypress run -e env=test
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: frontend/cypress/screenshots
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: frontend/cypress/videos
  api-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: backend
    - name: Load fixtures and schema
      env:
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails db:schema:load
        bundle exec bin/rails db:fixtures:load
    - name: Run rails backend
      env:
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails s &
    - name: run API tests
      run:
        npx newman run https://api.getpostman.com/collections/$COLLECTION_UID_YABS?apikey=$POSTMAN_KEY
      env:
        COLLECTION_UID_YABS: ${{secrets.COLLECTION_UID_YABS}}
        POSTMAN_KEY: ${{secrets.POSTMAN_KEY}}
