name: Unit

on: [push]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: yabs_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-interval 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: backend
    - name: Load database from schema
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails db:schema:load
    - name: Run unit tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: |
        cd backend
        bundle exec bin/rake

  backend-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: backend
    - name: Run rubocop linter
      run: |
        cd backend
        backend exec rubocop

  frontend-unit-tests:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: yabs_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-interval 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages
      run: |
        cd frontend
        yarn install
    - name: Run unit tests
      run: |
        cd frontend
        yarn test:unit

  frontend-lint:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: yabs_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-interval 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages
      run: |
        cd frontend
        yarn install
    - name: Run linter
      run: |
        cd frontend
        yarn lintnf
