name: Unit

on: [push]

jobs:
  backend-unit-tests:

    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: backend
    - name: Load database from schema
      run: |
        cd backend
        bundle exec bin/rails db:schema:load
    - name: Run unit tests
      run: |
        cd backend
        bundle exec bin/rake

  frontend-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages
      run: |
        cd frontend
        yarn install
    - name: Run unit tests
      run: |
        cd frontend
        yarn test:unit

  frontend-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages
      run: |
        cd frontend
        yarn install
    - name: Run linter
      run: |
        cd frontend
        yarn lintnf
